version: "3"
services:

  flask_webserver:
    container_name: flask_webserver
    image: cmpt-383-project_flask_webserver
    build:
      context: .
      dockerfile: python.Dockerfile

  spotify_cli_client:
    image: cmpt-383-project_spotify_cli_client
    container_name: spotify_cli_client
    tty: true
    stdin_open: true
    network_mode: "host"
    volumes: 
      - type: bind
        source: ./spotifyCLIOutput
        target: /app/out
    build:
      context: .
      dockerfile: java.Dockerfile


# Startup commands: 
#   docker-compose run --publish 8888:8888 --detach flask_webserver
#   docker-compose run spotify_cli_client
